### ISSUE TITLE
Choosing Ringbahn Direction makes no sense

### ISSUE THREAD

**Issue by bkfirmen** [FreiFahren/FreiFahren#110]
Today I reported a control in the S42 Ringbahn. In the reporting-form it is possible to choose the direction of the Ringbahn (Westend or Beusselstraße). This makes no sense, because the S42 is always driving counterclockwise and doesnt terminate. Maybe this input form can be surpressed, when S41 or S42 was choosen.

**Comment by johan-t** [comment]
@bkfirmen yes good idea thanks. Will implement it tomorrow
