### ISSUE TITLE
Support trams

### ISSUE THREAD

**Issue by rosahaj** [FreiFahren/FreiFahren#154]
According to #135, trams are currently unsupported. Would it be possible to support trams in the future? There seem to be plenty of reports in the Telegram group, particularly for MetroTrams.

**Comment by johan-t** [comment]
@rosahaj Thanks for opening a request, this is planned the issue why we have not added this yet is that there are a lot of tram stations this means we would have to retrain our NER model which is being used for the telegram bot, this will likely cause a decrease in accuracy as the pool of possible stations is going to increase. But we will find a solution and implement it soon.
