### ISSUE TITLE
Add compass

### ISSUE THREAD

**Issue by rosahaj** [FreiFahren/FreiFahren#161]
At the moment there's no way to reset the map orientation once changed (other than deleting the site data). I suggest adding a small compass, for example in the top right corner, which indicates what direction is North and resets the map orientation when pressed.

For reference, see the compass in the [Google Maps](https://play.google.com/web/store/apps/details?id=com.google.android.apps.maps&hl=de) and [OsmAnd~](https://osmand.net/) apps.

**Comment by johan-t** [comment]
@rosahaj Good idea, will implement this
