### ISSUE TITLE
Map attribution is on top

### ISSUE THREAD

**Issue by johan-t** [FreiFahren/FreiFahren#258]
On my Iphone 13 the map attribution is in the top right it should be at the bottom left.

<img src="https://uploads.linear.app/a17759f9-5817-4043-bf18-2a4ade636904/1b8059e4-9864-4e06-a692-a21370b14eb0/24aa81ce-889c-4cfb-b31a-1cae63eece19?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2ExNzc1OWY5LTU4MTctNDA0My1iZjE4LTJhNGFkZTYzNjkwNC8xYjgwNTllNC05ODY0LTRlMDYtYTY5Mi1hMjEzNzBiMTRlYjAvMjRhYTgxY2UtODg5Yy00Y2ZiLWIzMWEtMWNhZTYzZWVjZTE5IiwiaWF0IjoxNzMxOTUxODI1LCJleHAiOjMzMzAyNTExODI1fQ.OXOPNr276wD8qvAcO5SlHtE3FIHm58aRvJqAENQ5hL8 " alt="IMG_F96EEDE9A7CA-1.jpeg" width="1170" height="2532" />

**Comment by mclrc** [comment]
the issue with this are phone screens with rounded corners and software home/back/activities buttons or the iphone bar at the bottom. we can't really put it on the very bottom without overriding safe area margins and risking it being cut off, so it would have to float akwardly pretty far above the bottom screen border like this:

<img src="https://uploads.linear.app/a17759f9-5817-4043-bf18-2a4ade636904/02b9c87e-1cac-4331-adbb-6af343d95a51/4bd9a5df-c878-4e80-be2c-4c6b32d4e26f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2ExNzc1OWY5LTU4MTctNDA0My1iZjE4LTJhNGFkZTYzNjkwNC8wMmI5Yzg3ZS0xY2FjLTQzMzEtYWRiYi02YWYzNDNkOTVhNTEvNGJkOWE1ZGYtYzg3OC00ZTgwLWJlMmMtNGM2YjMyZDRlMjZmIiwiaWF0IjoxNzMyMDk2MDc3LCJleHAiOjMzMzAyNjU2MDc3fQ.ctgT9e9-Sd_eMIiwzRd6Eq9uEHuQofF6hRaIntlQzLA " alt="image.png" width="1320" height="2868" />

i think on the top it's way less intrusive

**Comment by johan-t** [comment]
Yeah agreed, I think it better when it is at the top. Close the issue if you like to.
