### ISSUE TITLE
Reports in List should be bigger

### ISSUE THREAD

**Issue by johan-t** [FreiFahren/FreiFahren#263]
As a lot of users are older it is important to have everything be readable. I think the reports in the report sheet are right about on the edge to be readable for me and I think some older users could struggle with this.

**Comment by mclrc** [comment]
are you sure? it's the standard font size. same size as whatsapp for me. i think we can reasonable expect people to read that and adjust their font settings if not, which they may already have, as i don't think it's a particularly small font size?

**Comment by johan-t** [comment]
@mclrc maybe it was just my perception as the web app font is quite big. But it is also fine for me if it stays the way it is. Just decide what you think is better.
