### ISSUE TITLE
Fix sorting order of stations in report modal

### ISSUE THREAD

**Issue by johan-t** [FreiFahren/FreiFahren#300]
The stations are being sorted alphabetically based on their id, they should be sorted based on their name.

**Comment by vinhyan** [comment]
Hi @johan-t! I can look into this issue.

**Comment by johan-t** [comment]
> Hi @johan-t! I can look into this issue.

Awesome, let me know if you have any issues setting up the dev environment or with anything else

**Comment by vinhyan** [comment]
Hi @johan-t! I was trying to get the backend to work and ran into the error below. Apparently `RISK_API_URL` env is needed here but I could not find this piece of information anywhere from the docs. Can you advise what this url should be?

<img width="1362" alt="Screenshot 2024-11-27 at 3 33 28 PM" src="https://github.com/user-attachments/assets/d5d63080-3af1-4310-a836-e8bd2be40609">

![image](https://github.com/user-attachments/assets/e558a260-29f3-4a1e-9c1f-e59ff30b7acd)

**Comment by johan-t** [comment]
Hey, this is for our "microservice" that will calculate the risk for each line. It is a bit harder to get running and even harder to modify at the moment. For now you can ignore this error as the risk microservice is not needed for most issues.

**Comment by vinhyan** [comment]
Hi @johan-t! 

Thank you for the clarifications. After studying the codebase, I have a couple of questions: 

As I set up my database locally (following the backend `README.md`), I started with an empty `ticket_info` table created by the script. When submitting a `report`, the `POST` route (`basics/inspectors`) checks the request `data` for hate speech using `checkHateSpeech`, which requires `CONTENT_MODERATION_SERVICE_URL`. Am I correct in assuming this URL refers to a "microservice" that is not publicly accessible, similar to `RISK_API_URL`? 

Currently, without `CONTENT_MODERATION_SERVICE_URL`, `PostInspector` is returning an `Internal Server Error`, which prevents generating any report data for use in `ReportsModal`.

![image](https://github.com/user-attachments/assets/7c0a9a7f-0c86-4722-975a-71025be26113)
![image](https://github.com/user-attachments/assets/a06f4f3f-df34-4e50-b088-c1c16f959adc)
![image](https://github.com/user-attachments/assets/e1134f38-4016-4c50-994b-c02bd09fb4bc)

I’m still familiarizing myself with the codebase, so there may be other areas I’ve missed. Any advice or guidance you can provide would be greatly appreciated.

Thank you!

**Comment by johan-t** [comment]
> Hi @johan-t!
> 
> Thank you for the clarifications. After studying the codebase, I have a couple of questions:
> 
> As I set up my database locally (following the backend `README.md`), I started with an empty `ticket_info` table created by the script. When submitting a `report`, the `POST` route (`basics/inspectors`) checks the request `data` for hate speech using `checkHateSpeech`, which requires `CONTENT_MODERATION_SERVICE_URL`. Am I correct in assuming this URL refers to a "microservice" that is not publicly accessible, similar to `RISK_API_URL`?
> 
> Currently, without `CONTENT_MODERATION_SERVICE_URL`, `PostInspector` is returning an `Internal Server Error`, which prevents generating any report data for use in `ReportsModal`.
> 
> ![image](https://private-user-images.githubusercontent.com/65751141/390595950-7c0a9a7f-0c86-4722-975a-71025be26113.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NzczNjAsIm5iZiI6MTczMjc3NzA2MCwicGF0aCI6Ii82NTc1MTE0MS8zOTA1OTU5NTAtN2MwYTlhN2YtMGM4Ni00NzIyLTk3NWEtNzEwMjViZTI2MTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA2NTc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzZTM1ZjYzODY0ZTcwMWU0YTI4OTEwZTc1MTM0NTA3ODQ1N2ZlOGQ2ZjdjYmQwYThkNGQwNmI2YzdjYTZkMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iI2IjWx7yKVaMxvETrSj063ox2OPmm4BjXbCxj2HMWI) ![image](https://private-user-images.githubusercontent.com/65751141/390596946-a06f4f3f-df34-4e50-b088-c1c16f959adc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NzczNjAsIm5iZiI6MTczMjc3NzA2MCwicGF0aCI6Ii82NTc1MTE0MS8zOTA1OTY5NDYtYTA2ZjRmM2YtZGYzNC00ZTUwLWIwODgtYzFjMTZmOTU5YWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA2NTc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NjAxNzNkNDcyZTdlZmI3Y2I1MjllNjMzOTY4MTNiMzg3YmY2NDhkMmYyY2Q5YmYzMjE2YjE4YjFiMzkyNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xgZ3_i0v9oyLh0zZNUDKKBbZAnCz5-URg9l1Tcv627Y) ![image](https://private-user-images.githubusercontent.com/65751141/390597557-e1134f38-4016-4c50-994b-c02bd09fb4bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NzczNjAsIm5iZiI6MTczMjc3NzA2MCwicGF0aCI6Ii82NTc1MTE0MS8zOTA1OTc1NTctZTExMzRmMzgtNDAxNi00YzUwLTk5NGItYzAyYmQwOWZiNGJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA2NTc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmOGQ0MDkyODAwNzFkN2RiNWU4NDM5ZDkxMDNmZjNhNjM1ZWIxMjU1Y2I3Mzk5OWQ0OGE1MmRhZTk2YTVmZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.anmTlDICDZAgBvOyVYfIz4p8umbjG0TrObSfB3Y8Gr8)
> 
> I’m still familiarizing myself with the codebase, so there may be other areas I’ve missed. Any advice or guidance you can provide would be greatly appreciated.
> 
> Thank you!

Hey, thanks for pointing this out. We can really do a better job of documenting the onboarding service. You are correct in assuming that the `CONTENT_MODERATION_SERVICE_URL` is pointing to a microservice. You can either access it with this url: http://88.99.56.234:9090 or you can run it locally using this guide: https://github.com/FreiFahren/FreiFahren/tree/main/packages/hate_speech_filter

**Comment by vinhyan** [comment]
Hi @johan-t! Thanks for the suggestion! I was finally able to get the project functioning. However, I wanted to clarify the issue: did you mean the order of the stations from the report form (accessed by clicking the "Melden" button), or from `ReportsModal` (via the "Reports" button on the left)?

Initially, I thought it was the latter, but after reviewing issue #301, I think you might have been referring to the former ("Meldon" button).

Thanks!

**Comment by johan-t** [comment]
> left)?

Hey, I meant the list of stations in the ReportForm. Sorry for the unclarity.
