### ISSUE TITLE
Replace Direction Keyword array with a spacy matcher

### ISSUE THREAD

**Issue by johan-t** [FreiFahren/FreiFahren#8]
We are currently identifying if a direction was mentioned based on an array of verbs and their different forms. This could be done more sophisticated using a [spacy matcher](https://spacy.io/api/matcher).
This would improve real world performance and make the code more maintainable.

**Comment by SeanAverS** [comment]
Hello, 

I am interested on working on this. Could I please be assigned? Thank you.
